const MockConstants = {
    mockDataOverride: true,
    mockUserLoc: {
        latitude: 41.8827,
        longitude: -87.6233
    },
    mockTrainTimeUsingDist: true,
    mockTime: 1634193800000,
    mockTrains: {
        'red': [
            {
                "staId": "41090",
                "stpId": "30211",
                "staNm": "Monroe",
                "stpDe": "Service toward Howard",
                "rn": "838",
                "rt": "Red",
                "destSt": "30173",
                "destNm": "Howard",
                "trDr": "1",
                "prdt": "2021-10-14T01:36:21",
                "arrT": "2021-10-14T01:37:21",
                "isApp": "1",
                "isSch": "0",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": "41.87404",
                "lon": "-87.62748",
                "heading": "0"
            },
            {
                "staId": "41090",
                "stpId": "30212",
                "staNm": "Monroe",
                "stpDe": "Service toward 95th/Dan Ryan",
                "rn": "937",
                "rt": "Red",
                "destSt": "30089",
                "destNm": "95th/Dan Ryan",
                "trDr": "5",
                "prdt": "2021-10-14T01:36:29",
                "arrT": "2021-10-14T01:39:29",
                "isApp": "0",
                "isSch": "0",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": "41.89166",
                "lon": "-87.62802",
                "heading": "178"
            },
            {
                "staId": "41090",
                "stpId": "30211",
                "staNm": "Monroe",
                "stpDe": "Service toward Howard",
                "rn": "836",
                "rt": "Red",
                "destSt": "30173",
                "destNm": "Howard",
                "trDr": "1",
                "prdt": "2021-10-14T01:36:43",
                "arrT": "2021-10-14T01:49:43",
                "isApp": "0",
                "isSch": "0",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": "41.79147",
                "lon": "-87.63109",
                "heading": "358"
            }
        ],
        'org': [
            {
                "staId": "40900",
                "stpId": "30176",
                "staNm": "Howard",
                "stpDe": "Service toward Midway",
                "rn": "523",
                "rt": "Org",
                "destSt": "30176",
                "destNm": "Midway",
                "trDr": "5",
                "prdt": "2021-10-14T01:38:39",
                "arrT": "2021-10-14T01:40:39",
                "isApp": "0",
                "isSch": "0",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": "42.03751",
                "lon": "-87.68069",
                "heading": "167"
            },
            {
                "staId": "40900",
                "stpId": "30175",
                "staNm": "Howard",
                "stpDe": "Service toward Loop",
                "rn": "523",
                "rt": "Org",
                "destSt": "0",
                "destNm": "Loop",
                "trDr": "1",
                "prdt": "2021-10-14T01:38:42",
                "arrT": "2021-10-14T01:50:42",
                "isApp": "0",
                "isSch": "1",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": null,
                "lon": null,
                "heading": null
            },
            {
                "staId": "40900",
                "stpId": "30176",
                "staNm": "Howard",
                "stpDe": "Service toward Midway",
                "rn": "522",
                "rt": "Org",
                "destSt": "0",
                "destNm": "Midway",
                "trDr": "5",
                "prdt": "2021-10-14T01:38:42",
                "arrT": "2021-10-14T02:02:42",
                "isApp": "0",
                "isSch": "1",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": null,
                "lon": null,
                "heading": null
            }
        ],
        'y': [
            {
                "staId": "40900",
                "stpId": "30176",
                "staNm": "Howard",
                "stpDe": "Service toward Howard",
                "rn": "523",
                "rt": "Y",
                "destSt": "30176",
                "destNm": "Howard",
                "trDr": "5",
                "prdt": "2021-10-14T01:38:39",
                "arrT": "2021-10-14T01:40:39",
                "isApp": "0",
                "isSch": "0",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": "42.03751",
                "lon": "-87.68069",
                "heading": "167"
            },
            {
                "staId": "40900",
                "stpId": "30175",
                "staNm": "Howard",
                "stpDe": "Service toward Skokie",
                "rn": "523",
                "rt": "Y",
                "destSt": "0",
                "destNm": "Skokie",
                "trDr": "1",
                "prdt": "2021-10-14T01:38:42",
                "arrT": "2021-10-14T01:50:42",
                "isApp": "0",
                "isSch": "1",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": null,
                "lon": null,
                "heading": null
            },
            {
                "staId": "40900",
                "stpId": "30176",
                "staNm": "Howard",
                "stpDe": "Service toward Howard",
                "rn": "522",
                "rt": "Y",
                "destSt": "0",
                "destNm": "Howard",
                "trDr": "5",
                "prdt": "2021-10-14T01:38:42",
                "arrT": "2021-10-14T02:02:42",
                "isApp": "0",
                "isSch": "1",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": null,
                "lon": null,
                "heading": null
            }
        ],
        'g': [
            {
                "staId": "40900",
                "stpId": "30176",
                "staNm": "Howard",
                "stpDe": "Service toward Cottage Grove",
                "rn": "523",
                "rt": "G",
                "destSt": "30176",
                "destNm": "Cottage Grove",
                "trDr": "5",
                "prdt": "2021-10-14T01:38:39",
                "arrT": "2021-10-14T01:40:39",
                "isApp": "0",
                "isSch": "0",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": "42.03751",
                "lon": "-87.68069",
                "heading": "167"
            },
            {
                "staId": "40900",
                "stpId": "30175",
                "staNm": "Howard",
                "stpDe": "Service toward Harlem/Lake",
                "rn": "523",
                "rt": "G",
                "destSt": "0",
                "destNm": "Harlem/Lake",
                "trDr": "1",
                "prdt": "2021-10-14T01:38:42",
                "arrT": "2021-10-14T01:50:42",
                "isApp": "0",
                "isSch": "1",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": null,
                "lon": null,
                "heading": null
            },
            {
                "staId": "40900",
                "stpId": "30176",
                "staNm": "Howard",
                "stpDe": "Service toward Cottage Grove",
                "rn": "522",
                "rt": "G",
                "destSt": "0",
                "destNm": "Cottage Grove",
                "trDr": "5",
                "prdt": "2021-10-14T01:38:42",
                "arrT": "2021-10-14T02:02:42",
                "isApp": "0",
                "isSch": "1",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": null,
                "lon": null,
                "heading": null
            }
        ],
        'blue': [
            {
                "staId": "40900",
                "stpId": "30176",
                "staNm": "Howard",
                "stpDe": "Service toward Loop",
                "rn": "523",
                "rt": "Blue",
                "destSt": "30176",
                "destNm": "Forest Park",
                "trDr": "5",
                "prdt": "2021-10-14T01:38:39",
                "arrT": "2021-10-14T01:40:39",
                "isApp": "0",
                "isSch": "0",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": "42.03751",
                "lon": "-87.68069",
                "heading": "167"
            },
            {
                "staId": "40900",
                "stpId": "30175",
                "staNm": "Howard",
                "stpDe": "Service toward O’Hare",
                "rn": "523",
                "rt": "Blue",
                "destSt": "0",
                "destNm": "O’Hare",
                "trDr": "1",
                "prdt": "2021-10-14T01:38:42",
                "arrT": "2021-10-14T01:50:42",
                "isApp": "0",
                "isSch": "1",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": null,
                "lon": null,
                "heading": null
            },
            {
                "staId": "40900",
                "stpId": "30176",
                "staNm": "Howard",
                "stpDe": "Service toward Loop",
                "rn": "522",
                "rt": "Blue",
                "destSt": "0",
                "destNm": "Forest Park",
                "trDr": "5",
                "prdt": "2021-10-14T01:38:42",
                "arrT": "2021-10-14T02:02:42",
                "isApp": "0",
                "isSch": "1",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": null,
                "lon": null,
                "heading": null
            }
        ],
        'brn': [
            {
                "staId": "41700",
                "stpId": "30383",
                "staNm": "Washington/Wabash",
                "stpDe": "Service at Outer Loop platform",
                "rn": "434",
                "rt": "Brn",
                "destSt": "30249",
                "destNm": "Kimball",
                "trDr": "1",
                "prdt": "2021-10-14T01:31:39",
                "arrT": "2021-10-14T01:37:39",
                "isApp": "0",
                "isSch": "0",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": "41.88505",
                "lon": "-87.6339",
                "heading": "178"
            },
            {
                "staId": "41700",
                "stpId": "30383",
                "staNm": "Washington/Wabash",
                "stpDe": "Service at Outer Loop platform",
                "rn": "435",
                "rt": "Brn",
                "destSt": "0",
                "destNm": "Kimball",
                "trDr": "1",
                "prdt": "2021-10-14T01:31:42",
                "arrT": "2021-10-14T01:54:42",
                "isApp": "0",
                "isSch": "1",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": null,
                "lon": null,
                "heading": null
            }
        ],
        'p': [
            {
                "staId": "40900",
                "stpId": "30176",
                "staNm": "Howard",
                "stpDe": "Service toward Loop",
                "rn": "523",
                "rt": "P",
                "destSt": "30176",
                "destNm": "Howard",
                "trDr": "5",
                "prdt": "2021-10-14T01:38:39",
                "arrT": "2021-10-14T01:40:39",
                "isApp": "0",
                "isSch": "0",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": "42.03751",
                "lon": "-87.68069",
                "heading": "167"
            },
            {
                "staId": "40900",
                "stpId": "30175",
                "staNm": "Howard",
                "stpDe": "Service toward Linden",
                "rn": "523",
                "rt": "P",
                "destSt": "0",
                "destNm": "Linden",
                "trDr": "1",
                "prdt": "2021-10-14T01:38:42",
                "arrT": "2021-10-14T01:50:42",
                "isApp": "0",
                "isSch": "1",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": null,
                "lon": null,
                "heading": null
            },
            {
                "staId": "40900",
                "stpId": "30176",
                "staNm": "Howard",
                "stpDe": "Service toward Loop",
                "rn": "522",
                "rt": "P",
                "destSt": "0",
                "destNm": "Howard",
                "trDr": "5",
                "prdt": "2021-10-14T01:38:42",
                "arrT": "2021-10-14T02:02:42",
                "isApp": "0",
                "isSch": "1",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": null,
                "lon": null,
                "heading": null
            }
        ],
        'pink': [
            {
                "staId": "40900",
                "stpId": "30176",
                "staNm": "Howard",
                "stpDe": "Service toward Loop",
                "rn": "523",
                "rt": "Pink",
                "destSt": "30176",
                "destNm": "54th/Cermak",
                "trDr": "5",
                "prdt": "2021-10-14T01:38:39",
                "arrT": "2021-10-14T01:40:39",
                "isApp": "0",
                "isSch": "0",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": "42.03751",
                "lon": "-87.68069",
                "heading": "167"
            },
            {
                "staId": "40900",
                "stpId": "30175",
                "staNm": "Howard",
                "stpDe": "Service toward 54th/Cermak",
                "rn": "523",
                "rt": "Pink",
                "destSt": "0",
                "destNm": "Loop",
                "trDr": "1",
                "prdt": "2021-10-14T01:38:42",
                "arrT": "2021-10-14T01:50:42",
                "isApp": "0",
                "isSch": "1",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": null,
                "lon": null,
                "heading": null
            },
            {
                "staId": "40900",
                "stpId": "30176",
                "staNm": "Howard",
                "stpDe": "Service toward Loop",
                "rn": "522",
                "rt": "Pink",
                "destSt": "0",
                "destNm": "54th/Cermak",
                "trDr": "5",
                "prdt": "2021-10-14T01:38:42",
                "arrT": "2021-10-14T02:02:42",
                "isApp": "0",
                "isSch": "1",
                "isDly": "0",
                "isFlt": "0",
                "flags": null,
                "lat": null,
                "lon": null,
                "heading": null
            }
        ]
    }
}

export default MockConstants